import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import TrendingSlider from "./components/trendingSlider/TrendingSlider";

const lato = Lato({
  subsets: ["latin"],
  weight: "400", 
});

export const metadata = {
  title: "Receipe App",
  description: "Generated by AKanksha",
  icons:{
    icon:['https://img.freepik.com/free-vector/hand-drawn-design-world-food-day_23-2148648454.jpg?size=626&ext=jpg&ga=GA1.1.161403668.1709701247&semt=ais']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar/>
        {children}
        <div className="mt-[1rem]">
          <TrendingSlider/>
        </div>
      </body>
    </html>
  );
}